[package]
name = "witchcraft-log"
version = "0.2.1"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"
description = "A structured logging facade for Witchcraft servers"
repository = "https://github.com/palantir/witchcraft-rust-logging"
categories = ["development-tools::debugging"]

[dependencies]
conjure-error = "0.6"
erased-serde = "0.3"
lazycell = "1.0"
log = "0.4"
serde = "1.0"

[dev-dependencies]
serde_test = "1.0"
serde-value = "0.6"
